### ISSUE TITLE
nothing is shown?

### ISSUE THREAD

**Issue by rezad1393** [jesperbakhandskemager/Return-Invidious-Dislike-Count#2]
I installed this and I see it enabled for the invidious instance but I don't see any data shown.
test url:
https://yewtu.be/watch?v=D_V3OsHtXvU

**Comment by jesperbakhandskemager** [comment]
Yes, it seems invidious was updated and broke compatibility

**Comment by jesperbakhandskemager** [comment]
I updated the script, and it should now work again.
Thanks for the notice
